# Generated by Django 3.1.7 on 2021-04-15 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ('responded',)},
        ),
        migrations.AlterField(
            model_name='issue',
            name='message',
            field=models.TextField(max_length=300),
        ),
    ]
