# Generated by Django 3.1.7 on 2021-04-15 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rents', '0002_auto_20210408_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rent',
            options={'ordering': ('-rent_starts',)},
        ),
    ]
