# Generated by Django 3.1.7 on 2021-04-08 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_delete_carimage'),
        ('rents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_car', to='car.car'),
        ),
        migrations.AlterField(
            model_name='rent',
            name='price',
            field=models.IntegerField(),
        ),
    ]
